blank_issues_enabled: false
contact_links:
  - name: ğŸ“ GuÃ­a de contribuciÃ³n / Contribution guide
    url: https://github.com/bert0h-dev/menvitta-backend/blob/main/CONTRIBUTING.md
    about: Lee las reglas y buenas prÃ¡cticas antes de contribuir. / Read the rules and best practices before contributing.